services:
  postgres:
    image: postgres
    container_name: landing-zone-postgres
    restart: always
    ports:
     - "5432:5432"
    shm_size: 128mb
    environment:
      POSTGRES_USERNAME: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: yfinance-data-platform
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse_data:/var/lib/clickhouse

#   airflow:
#     image: apache/airflow:2.5.1
#     container_name: airflow
#     restart: always
#     environment:
#       - AIRFLOW__CORE__EXECUTOR=LocalExecutor
#       - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://user:password@postgres:5432/airflow
#     ports:
#       - "8080:8080"
#     depends_on:
#       - postgres

#   dbt:
#     image: ghcr.io/dbt-labs/dbt-postgres:latest
#     container_name: dbt
#     restart: always
#     volumes:
#       - ./dbt_project:/usr/app/dbt_project
#     depends_on:
#       - clickhouse
#       - postgres

volumes:
  postgres_data:
  clickhouse_data:
